### ISSUE TITLE
ERROR [vcstools] Tarball download unpack failed: file could not be opened successfully[/vcstools]

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [vcstools/wstool#125]
I am installing ROS from source:
http://wiki.ros.org/melodic/Installation/Source
When I run 
`wstool init -j8 src melodic-desktop-full.rosinstall`
where ` melodic-desktop-full.rosinstall` is : 
```
- tar:
    local-name: actionlib
    uri: https://github.com/ros-gbp/actionlib-release/archive/release/melodic/actionlib/1.11.13-0.tar.gz
    version: actionlib-release-release-melodic-actionlib-1.11.13-0
- tar:
...

```

wstool is not able to download and extract the stuff, I get this error for example:

``
[rqt_publisher] Fetching https://github.com/ros-gbp/rqt_publisher-release/archive/release/melodic/rqt_publisher/0.4.8-0.tar.gz (version rqt_publisher-release-release-melodic-rqt_publisher-0.4.8-0) to /home/francesco/ros_catkin_ws/src/rqt_publisher
ERROR [vcstools] Tarball download unpack failed: file could not be opened successfully[/vcstools]
```
For each package. Any help?

Thank you in advance,

Francesco Saverio
